---
title: "FinalProj_Draft_2"
output: html_document
author: Rebecca Connelly
---

```{r setup}
library(tidyverse)
library(DataExplorer)
library(esquisse)
library(ggplot2)
library(plotly)
library(sf)
library(devtools)
library(usmapdata)
library(usmap)
library(ggplot2)
library(maps)
library(waffle)

```


```{r read in data}
childhealthdata <- read_csv("C:/Users/rebec/Documents/GitHub/FinalProject_A/2019-2020 National Survey of Children's Health (NSCH)/ChildHealthData_Edited_1920_ONLY.csv")

names(childhealthdata) <- make.names(names(childhealthdata), unique=TRUE)
```

```{r editing variables}
#race 

childhealthdata$Race = as.factor(childhealthdata$Race) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(RaceCat = recode(Race, 
  "1" = "Hispanic",
  "2" = "White",
  "3" = "Black",
  "4" = "Asian",
  "5" = "Other",
  "99" = "Unknown",
  .default = "Unknown"))

#health status
  
childhealthdata <- mutate(childhealthdata,
          ChildHealthStatus = 
          recode_factor(ChildHealthStatus_1920, 
  "3" = "Fair or Poor",
  "2" = "Good",
  "1" = "Excellent or Very Good",
  "99" = "Unknown",
  .ordered = TRUE,
  .default = "Unknown"))

#sex

childhealthdata$Sex1920 = as.factor(childhealthdata$Sex1920) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(Sex = recode(Sex1920, 
  "1" = "Male",
  "2" = "Female",
  "99" = "Missing",
  .default = "Missing"))

#flourishing status 

childhealthdata <- childhealthdata %>% mutate(FlourishStatus0to5 = recode_factor(flrish0to5_1920, 
  "1" = "Meets 0-2 Items",
  "2" = "Meets 3 Items",
  "3" = "Meets all 4 Items",
  "4" = "Never",
  "90" = "NA, Over 5",
"95" =  "NA, under 6m",
  "99" = "Unknown",
  .ordered = TRUE,
  .default = "Unknown"))


childhealthdata <- childhealthdata %>% mutate(FlourishStatus6to17 = recode_factor(flrish6to17_1920, 
  "1" = "Meets 0-1 Items",
  "2" = "Meets 2 Items",
  "3" = "Meets all 3 Items",
  "90" = "NA, Under 5",
  "99" = "Unknown",
  .ordered = TRUE,
  .default = "Unknown"))

#forgoing care

childhealthdata$ForgoneCare_1920 = as.factor(childhealthdata$ForgoneCare_1920) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(ForegoneCare = recode_factor(ForgoneCare_1920, 
  "1" = "Went Without",
  "2" = "Received Need Care",
  "99" = "Unknown",
  .default = "Unknown"))

#behavioral probs 

childhealthdata <- childhealthdata %>% mutate(behaviorprob = recode_factor(behavior_1920, 
  "1" = "No",
  "2" = "Used to",
  "3" = "Yes",
  "99" = "Unknown",
  "96" = "NA Under 3",
  .ordered = TRUE,
  .default = "Unknown"))

#neighborhood safe

childhealthdata <- childhealthdata %>% mutate(NbhdSafe = recode_factor(NbhdSafe_1920,
  "3" = "Disagree",
  "2" = "Somewhat Agree",
  "1" = "Definitely Agree",
  "99" = "Unknown",
  .ordered = TRUE,
  .default = "Unknown"))

#poverty level

childhealthdata <- childhealthdata %>% mutate(povlevel = recode_factor(povlev4_1920, 
  "1" = "Below 100% FPL",
  "2" = "100-199% FPL",
  "3" = "200-399% FPL",
  "4" = "Greater than 400% FPL",
  .ordered = TRUE,
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(povlevelgrouped = recode(povlev4_1920, 
  "1" = "Below 200% FPL",
  "2" = "Below 200% FPL",
  "3" = "200% or above FPL",
  "4" = "200% or above FPL",
  .default = "Unknown"))

#emotional support 

childhealthdata <- childhealthdata %>% mutate(EmSupport_1920 = recode_factor(EmSupport_1920,
  "1" = "Yes",
  "2" = "No",
  "99" = "Unknown",
  .default = "Unknown"))

#insured 

childhealthdata <- childhealthdata %>% mutate(InsGap_1920 = recode(InsGap_1920, 
  "1" = "Insured",
  "2" = "Periods Uninsured",
  "99" = "Unknown",
  .default = "Unknown"))

#mothers mental health

childhealthdata <- childhealthdata %>% mutate(MotherMH = recode_factor(MotherMH_1920,
  "1" = "Excellent or Very Good",
  "2" = "Good",
  "3" = "Fair or Poor",
  "99" = "Unknown",
  "95" = "No Mother in Home",
  .ordered = TRUE,
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(AceCount = recode_factor(ACEct_1920,
  "0" = "0",
  "1" = "1",
  "2" = "2",
  "3" = "3",
  "4" = "4",
  "5" = "5",
  "6" = "6", 
  "&" = "7",
  "8" = "8",
  "9" = "9",
  "10" = "10",
  "99" = "Missing",
  .ordered = TRUE,
  .default = "Unknown"))

#ACEct_1920 - NOT making categorical 
```

```{r creating new variables: filters}
#filters
FiveAndUnder <- childhealthdata %>%
  filter(Child.Age <= 5)

NewJersey <- childhealthdata %>%
  filter(State.FIPS.Code == "34")

Poor <- childhealthdata %>%
  filter(povlevel == "Less than 200% FPL")

MissedNeededCare <- childhealthdata %>%
  filter(ForegoneCare == "Yes")

parentEmoSup <- childhealthdata %>%
  filter(SomeoneEmoSup == 1)

yesbehaviorprobsALL <- childhealthdata %>%
  filter(behavior_1920 == "Yes")

White <- childhealthdata %>%
  filter(RaceCat == "White")

Black <- childhealthdata %>%
  filter(RaceCat == "Black")

Asian <- childhealthdata %>%
  filter(RaceCat == "Asian")

Hispanic <- childhealthdata %>%
  filter(RaceCat == "Hispanic")

OtherRace <- childhealthdata %>%
  filter(RaceCat == "Other")

```

```{r new variables: grouped}

#creating new variables 

flourishing6to17 <- childhealthdata %>% 
  group_by(FlourishStatus6to17) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

MissedCarebyState <- MissedNeededCare %>%
  group_by(State.FIPS.Code) %>%
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

uninsured <- childhealthdata %>%
  filter(InsGap_1920 == "Periods Uninsured")

uninsuredgrouped <- uninsured %>% 
  group_by(RaceCat) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

databyrace <- childhealthdata %>% 
  group_by(RaceCat) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)
```


##Visualizing 

```{r missed needed care}
#missed needed care by povery level 

childhealthdata %>%
 filter(!(ForegoneCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = ForegoneCare, fill = povlevel) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "cividis", 
 direction = 1) +
 labs(x = "Missed Out on Needed Care", y = "Proportion of Children", title = "Children Who Did Not Receive Needed Care by Poverty Level", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Poverty Level") +
 theme_minimal()

#inNJ
NewJersey %>%
 filter(!(ForegoneCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = ForegoneCare, fill = povlevelgrouped) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "cividis", 
 direction = 1) +
 labs(x = "Missed Out on Needed Care", y = "Proportion of Children", title = "Children in NJ Who Did Not Receive Needed Care by Poverty Level", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Poverty Level") +
 theme_minimal()
```

```{r ACES}
childhealthdata %>% 
  filter(!(FlourishStatus6to17 %in% "Unknown")) %>%
  filter(!(FlourishStatus6to17 %in% "NA, Under 5")) %>%
  filter(!(AceCount %in% "Missing")) %>%
ggplot() +
 aes(x = FlourishStatus6to17, fill = AceCount) +
 geom_bar(position = "fill") +
 scale_fill_hue(direction = 1) +
 labs(x = "Flourishing Items Met", y = "Children", title = "Flourishing Status & Adverse Childhood Experiences (ACE)",
 subtitle = "Count of Children in the US Meeting Flourishing Criteria by Number of Adverse Childhood Experiences", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()
#^ prior ACE visual, but didn't make ACE factors. not working right 

#inNJ
NewJersey$ACECount <- factor(NewJersey$ACECount,
  levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Missing"))

NewJersey %>%
  filter(!(ChildHealthStatus %in% "Unknown")) %>%
  filter(!(ACECount %in% "Missing")) %>%
ggplot() +
 aes(x = ChildHealthStatus, fill = ACECount) +
 geom_bar(position = "fill") +
 scale_fill_hue(direction = 1) +
 labs(x = "Health Status", y = "Number of Children", title = "Overall Health Status & Adverse Childhood Experiences (ACE)", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()

#ACE by Race

ggplot(Black) +
 aes(x = AceCount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experiences: Black Children", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: Black Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(White) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: White Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(Asian) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: Asian Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(Hispanic) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience",
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: Hispanic Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(OtherRace) +
 aes(x = ACEct_1920) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience: Other Race", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race", caption = "Based on National Survey of Children's Health, 2019-2020")

#ACEbyRACE one plot 

dataforACEplot$RaceCat <- factor(dataforACEplot$RaceCat,  
levels = c("Asian", "Hispanic", "Other", "White", "Black", "Unknown"))

dataforACEplot %>%
 filter(!(RaceCat %in% "Unknown")) %>%
 filter(!(ACECount %in% "Missing")) %>%
 ggplot() +
 aes(x = RaceCat, fill = ACECount) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", 
 direction = 1) +
 labs(x = "Race", y = "Proportion of Children", title = "Adverse Childhood Experiences (ACE) by Race in the US", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()

```

```{r insurance}
#Insurance and needed care 
childhealthdata$WentWithoutCare <- factor(childhealthdata$WentWithoutCare,
  levels = c("No", "Yes", "Unknown"))

#needed care by insurance status
childhealthdata %>%
 filter(!(InsGap_1920 %in% "Unknown")) %>%
 filter(!(ForegoneCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = ForegoneCare, fill = InsGap_1920) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", direction = 1) +
 labs(x = "Whether Child Missed out on Needed Care", 
 y = "Proportion of Children", title = "Children Receiving Necessary Care by Insurance Status", caption = "Based on National Survey of Children's Health, 2019-2020", 
 fill = "Insured Status") +
 theme_minimal()

#inNJ
NewJersey %>%
 filter(!(InsGap_1920 %in% "Unknown")) %>%
 filter(!(WentWithoutCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = WentWithoutCare, fill = InsGap_1920) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", direction = 1) +
 labs(x = "Whether Child Missed out on Needed Care", 
 y = "Proportion of Children", title = "Children in New Jersey Receiving Care by Insurance Status", caption = "Based on National Survey of Children's Health, 2019-2020",
 fill = "Insured Status") +
 theme_minimal()

#plot showing over 50% of poor are uninsured 

NewJersey %>%
 filter(!(InsGap_1920 %in% "Unknown")) %>%
 ggplot() +
 aes(x = InsGap_1920, fill = povlevel) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", 
 direction = 1) +
 labs(x = "Insurance Status", y = "Percentage", title = "Insurance Status and Poverty Level in New Jersey", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Poverty Level") +
 coord_flip() +
 theme_minimal()
```

```{r}
# VectorWhite %>% count(ChildHealthStatus)
WentWithoutWaffle <- c(Yes = 1, No = 44)

# Waffle chart
waffle(WentWithoutWaffle, rows = 5,
       legend_pos = "bottom")

#waffles for Race and Health Status

#WHITE
FlrishWhiteWaffle <- c("0-1 Items" = 19.1, "2 Items" = 19.4, "All 3 Items" = 61.5)

waffle(FlrishWhiteWaffle, rows = 10,
       legend_pos = "bottom")
#BLACK
FlrishBlackWaffle <- c("0-1 Items" = 20, "2 Items" = 18.8, "All 3 Items" = 61.2)

waffle(FlrishBlackWaffle, rows = 10,
       legend_pos = "bottom")

#HISPANIC
FlrishHispanicWaffle <- c("0-1 Items" = 16.8, "2 Items" = 19.6, "All 3 Items" = 63.6)

waffle(FlrishHispanicWaffle, rows = 10,
       legend_pos = "bottom")

#ASIAN
FlrishAsianWaffle <- c("0-1 Items" = 11.8, "2 Items" = 14.8, "All 3 Items" = 73.4)

waffle(FlrishAsianWaffle, rows = 10,
       legend_pos = "bottom")

#Poverty Waffle
NJPovWaffle <- c("Less than 200% FPL" = 24.4, "200% FPL or Greater" = 75.6)

waffle(NJPovWaffle, rows = 10,
       legend_pos = "bottom")

#neededcare 

NJCareWaffle <- c("Missed Out on Needed Care" = 2.2, "Received or Did Not Need Care" = 97.8)

waffle(NJCareWaffle, rows = 10,
       legend_pos = "bottom")

#uninsuredpoverty
#proportion of poor uninsured

NJpoor <- NewJersey %>%
  filter(povlevel == "Less than 200% FPL")

NJInsPovWaffle <- c("Insured" = 87, "Not Consistently Insured" = 13)

waffle(NJInsPovWaffle, rows = 10,
       legend_pos = "bottom")


```


```{r}
#exploring scatter 
ggplot(childhealthdata) + # data
  aes(x = ACEct_1920, y = FlourishStatus6to17) + # variables
  geom_point()
#^still looks like a line 

```

