---
title: "FinalDraft1"
output: pdf_document
author: Rebecca Connelly
---

```{r setup, }
library(tidyverse)
library(DataExplorer)
library(esquisse)
library(plotly)
library(sf)
library(devtools)
library(usmapdata)
library(usmap)
library(ggplot2)
library(maps)
library(waffle)


```


```{r read in data}
childhealthdata <- read_csv("C:/Users/rebec/Documents/GitHub/FinalProject_A/2019-2020 National Survey of Children's Health (NSCH)/ChildHealthData_Edited_1920_ONLY.csv")

introduce(childhealthdata)
#fixing column names 

names(childhealthdata) <- make.names(names(childhealthdata), unique=TRUE)

```

```{r editing variables}

#race 

childhealthdata$Race = as.factor(childhealthdata$Race) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(RaceCat = recode(Race, 
  "1" = "Hispanic",
  "2" = "White",
  "3" = "Black",
  "4" = "Asian",
  "5" = "Other",
  "99" = "Unknown",
  .default = "Unknown"))

#health status

childhealthdata$ChildHealthStatus_1920 = as.factor(childhealthdata$ChildHealthStatus_1920) # converting to categorical

factor_ChildHealthStatus_1920 <- factor(ChildHealthStatus_1920, order = TRUE, levels = c("Fair or Poor", "Good", "Excellent or Very Good") )

childhealthdata <- childhealthdata %>% mutate(ChildHealthStatus = recode(ChildHealthStatus_1920, 
  "1" = "Excellent or Very Good",
  "2" = "Good",
  "3" = "Fair or Poor",
  "99" = "Unknown",
  .default = "Unknown"))

#sex

childhealthdata$Sex1920 = as.factor(childhealthdata$Sex1920) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(Sex = recode(Sex1920, 
  "1" = "Male",
  "2" = "Female",
  "99" = "Missing",
  .default = "Missing"))

#states

childhealthdata$State.FIPS.Code = as.factor(childhealthdata$State.FIPS.Code) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(State = recode(State.FIPS.Code, 
  "1" = "AL",
"2" = "AK",
"4" = "AZ",
"5" = "AR",
"6" = "CA",
"8" = "CO",
"9" = "CT",
"10" = "DE",
"12" = "FL",
"13" = "GA",
"15" = "HI",
"16" = "ID",
"17" = "IL",
"18" = "IN",
"19" = "IA",
"20" = "KS",
"21" = "KY",
"22" = "LA",
"23" = "ME",
"24" = "MD",
"25" = "MA",
"26" = "MI",
"27" = "MN",
"28" = "MS",
"29" = "MO",
"30" = "MT",
"31" = "NE",
"32" = "NV",
"33" = "NH",
"34" = "NJ",
"35" = "NM",
"36" = "NY",
"37" = "NC",
"38" = "ND",
"39" = "OH",
"40" = "OK",
"41" = "OR",
"42" = "PA",
"44" = "RI",
"45" = "SC",
"46" = "SD",
"47" = "TN",
"48" = "TX",
"49" = "UT",
"50" = "VT",
"51" = "VA",
"53" = "WA",
"54" = "WV",
"55" = "WI",
"56" = "WY",
"60" = "AS",
"66" = "GU",
"69" = "MP",
"72" = "PR",
"78" = "VI",
  "99" = "Unknown",
  .default = "Unknown"))

#flourishing status

childhealthdata$flrish0to5_1920 = as.factor(childhealthdata$flrish0to5_1920) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(FlourishStatus0to5 = recode(flrish0to5_1920, 
  "1" = "Meets 0-2 Items",
  "2" = "Meets 3 Items",
  "3" = "Meets all 4 Items",
  "4" = "Never",
  "90" = "NA, Over 5",
"95" =  "NA, under 6m",
  "99" = "Unknown",
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(FlourishStatus6to17 = recode(flrish6to17_1920, 
  "1" = "Meets 0-1 Items",
  "2" = "Meets 2 Items",
  "3" = "Meets all 3 Items",
  "90" = "NA, Under 5",
  "99" = "Unknown",
  .default = "Unknown"))

#forgoing care

childhealthdata$ForgoneCare_1920 = as.factor(childhealthdata$ForgoneCare_1920) # converting to categorical

childhealthdata <- childhealthdata %>% mutate(WentWithoutCare = recode(ForgoneCare_1920, 
  "1" = "Yes",
  "2" = "No",
  "99" = "Unknown",
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(behavior_1920 = recode(behavior_1920, 
  "1" = "No",
  "2" = "Used to",
  "3" = "Yes",
  "99" = "Unknown",
  "96" = "NA Under 3",
  .default = "Unknown"))

childhealthdata <- transform(childhealthdata,
  NbhdSafe_1920 = factor(NbhdSafe_1920))

childhealthdata <- childhealthdata %>% mutate(NbhdSafe_1920 = recode(NbhdSafe_1920, 
  "1" = "Definitely Agree",
  "2" = "Somewhat Agree",
  "3" = "Somewhat/Definitely Disagree",
  "99" = "Unknown",
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(povlevel = recode(povlev4_1920, 
  "1" = "Less than 200% FPL",
  "2" = "Less than 200% FPL",
  "3" = "200% FPL or greater",
  "4" = "200% FPL or greater",
  .default = "Unknown"))


childhealthdata <- childhealthdata %>% mutate(EmSupport_1920 = recode(EmSupport_1920, 
  "1" = "Yes",
  "2" = "No",
  "99" = "Unknown",
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(InsGap_1920 = recode(InsGap_1920, 
  "1" = "Consistently Insured",
  "2" = "Uninsured or periods without coverage",
  "99" = "Unknown",
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(MotherMH_1920 = recode(MotherMH_1920, 
  "1" = "Excellent or Very Good ",
  "2" = "Good",
  "3" = "Fai or Poor",
  "99" = "Unknown",
  "95" = "No Mother in Home",
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(ACECount = recode(ACEct_1920, 
  "1" = "1",
  "0" = "0",
  "2" = "2",
  "3" = "3",
  "4" = "4",
  "5" = "5",
  "6" = "6",
  "7" = "7",
  "8" = "8",
  "9" = "9",
  "10" = "10",
  "99" = "Missing"))
```

```{r creating new variables}

#filters
FiveAndUnder <- childhealthdata %>%
  filter(Child.Age <= 5)

NewJersey <- childhealthdata %>%
  filter(State == "NJ")

Poor <- childhealthdata %>%
  filter(povlevel == "Less than 200% FPL")

MissedNeededCare <- childhealthdata %>%
  filter(WentWithoutCare == "Yes")

parentEmoSup <- childhealthdata %>%
  filter(SomeoneEmoSup == 1)

yesbehaviorprobsunder5 <- FiveAndUnder %>%
  filter(behavior_1920 == "Yes")

yesbehaviorprobsALL <- childhealthdata %>%
  filter(behavior_1920 == "Yes")

White <- childhealthdata %>%
  filter(RaceCat == "White")

Black <- childhealthdata %>%
  filter(RaceCat == "Black")

Asian <- childhealthdata %>%
  filter(RaceCat == "Asian")

Hispanic <- childhealthdata %>%
  filter(RaceCat == "Hispanic")

OtherRace <- childhealthdata %>%
  filter(RaceCat == "Other")

#creating new variables 


flourishing6to17 <- childhealthdata %>% 
  group_by(FlourishStatus6to17) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)


MissedCarebyState <- MissedNeededCare %>%
  group_by(State) %>%
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)


```

## Visualizing 
```{r flourishing visual histogram}


flourishplot6to17 <- ggplot(flourishing6to17, aes(x = FlourishStatus6to17, y = children, fill = children)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_b(name="Number of Children") +
  labs(title = "Frequency of 'Flourishing' Status in Children", x = "Frequency", y = "Number of Children")

#not interesting - most sometimes or usually
```

```{r missed needed care}
#histogram
missingcareplot <- ggplot(MissedCarebyState, aes(x = State, y = children, fill = children)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_b(name="Number of Children") + coord_flip() +
  labs(title = "Number of Children who Missed Needed Care", x = "State", y = "Number of Children")

missingcareplot

#mapping 

#because in my original data set I renamed the states column.. re-read it and left that column. 
TESTchildhealthdata <- read_csv("C:/Users/rebec/Documents/GitHub/FinalProject_A/2019-2020 National Survey of Children's Health (NSCH)/ChildHealthData_Edited_1920_ONLY.csv")

names(TESTchildhealthdata) <- make.names(names(TESTchildhealthdata), unique=TRUE)

TESTchildhealthdata <- TESTchildhealthdata %>% mutate(WentWithoutCare = recode(ForgoneCare_1920, 
  "1" = "Yes",
  "2" = "No",
  "99" = "Unknown",
  .default = "Unknown"))

TESTMissedNeededCare <- TESTchildhealthdata %>%
  filter(WentWithoutCare == "Yes")

TESTMissedCarebyState <- TESTMissedNeededCare %>%
  group_by(State.FIPS.Code) %>%
  count() %>% arrange(desc(n)) %>%
  rename("children" = n) %>%
  rename("fips" = "State.FIPS.Code")

map_with_data(TESTMissedCarebyState, values = "children", include = c(), exclude = c(), na = NA)

plot_usmap(
regions = c("states"),
data = data.frame(TESTMissedCarebyState),
values = "children",
theme = theme_void(),
label_color = "black",
) +
  labs(title = "Number of Children Who Did not Receive Needed Care by State",
       subtitle = "Source: National Survey of Children's Health: 2019-2020")


#foudn on CRAN here: https://cran.r-project.org/web/packages/usmap/usmap.pdf

```

```{r forgone needed care}
forgonebysexplot <- ggplot(childhealthdata) +
  geom_bar(aes(x = WentWithoutCare, fill = Sex), position = "fill")

ggplot(childhealthdata) +
  geom_bar(aes(x = RaceCat, fill = FlourishStatus6to17), position = "dodge")

ggplot(childhealthdata) +
  geom_bar(aes(x = RaceCat, fill = NbhdSafe_1920))

#^TRY SEPARATING THESE GRAPHS OUT

ggplot(White) +
  geom_bar(aes(x = RaceCat, fill = ChildHealthStatus))


```

```{r race}
#health status
ggplot(White) +
  geom_bar(aes(x = RaceCat, fill = ChildHealthStatus))
ggplot(Black) +
  geom_bar(aes(x = RaceCat, fill = ChildHealthStatus))
ggplot(Hispanic) +
  geom_bar(aes(x = RaceCat, fill = ChildHealthStatus))
#^not noticable difference

ggplot(White) +
  geom_bar(aes(x = RaceCat, fill = FlourishStatus6to17), position = "dodge")

```


```{r behavioral problems}

behaviorprobs <- FiveAndUnder %>% 
  group_by(behavior_1920) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

#^not interesting, majority "no" or "unknown" 

ggplot(behaviorprobs, aes(x = behavior_1920, y = children, fill = children)) +
     geom_bar(stat = "identity") +
     scale_fill_viridis_b(name="Number of Children") +
     labs(title = "Children with Behavioral Problems Under 5", x = "Frequency", y = "Number of Children")

yesbehaviorprobsALL %>% 
  group_by(EmSupport_1920) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)


```

```{r variables by poverty}

#missed care by FPL
carebypoverty <- MissedNeededCare %>% 
  group_by(povlevel) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

ggplot(carebypoverty, aes(x = povlevel, y = children, fill = children)) +
     geom_bar(stat = "identity") +
     scale_fill_viridis_b(name="Number of Children") +
     labs(title = "Children Who Did not Receive Needed Care by Poverty Level", x = "Poverty Level", y = "Number of Children")

#proportional missed care by poverty

childhealthdata %>%
 filter(!(WentWithoutCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = WentWithoutCare, fill = povlevel) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "cividis", 
 direction = 1) +
 labs(x = "Missed Out on Needed Care", y = "Proportion of Children", title = "Children Who Did Not Receive Needed Care by Poverty Level", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Poverty Level") +
 theme_minimal()

#inNJ
NewJersey %>%
 filter(!(WentWithoutCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = WentWithoutCare, fill = povlevel) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "cividis", 
 direction = 1) +
 labs(x = "Missed Out on Needed Care", y = "Proportion of Children", title = "Children in NJ Who Did Not Receive Needed Care by Poverty Level", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Poverty Level") +
 theme_minimal()

#behavior problem by FPL

BehavbyPov <- yesbehaviorprobsALL %>% 
  group_by(povlevel) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

BehavbyPovALL <- yesbehaviorprobsALL %>% 
  group_by(povlevel) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

ggplot(BehavbyPovALL, aes(x = povlevel, y = children, fill = children)) +
     geom_bar(stat = "identity") +
     scale_fill_viridis_b(name="Number of Children") +
     labs(title = "Children with Behavioral Problems by Poverty Level", x = "Poverty Level", y = "Number of Children")

```

```{r all children}

#behavior 
behaviorprobsALL <- childhealthdata %>% 
  group_by(behavior_1920) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

yesbehaviorprobsALL %>% 
  group_by(povlevel) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

childhealthdata %>% 
  group_by(NbhdSafe_1920) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)


```

```{r health status}

FiveAndUnder %>% 
  group_by(ChildHealthStatus) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

ggplot(FiveAndUnder) +
  geom_bar(aes(x = ChildHealthStatus, fill = EmSupport_1920))

ggplot(FiveAndUnder) +
  geom_bar(aes(x = ChildHealthStatus, fill = povlevel))


```

```{r emo support}
ggplot(childhealthdata) +
  geom_bar(aes(x = ChildHealthStatus, fill = EmSupport_1920))

ggplot(childhealthdata) +
  geom_bar(aes(x = behavior_1920, fill = EmSupport_1920))


```

```{r insurance}
childhealthdata %>% 
  group_by(InsGap_1920) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

uninsured <- childhealthdata %>%
  filter(InsGap_1920 == "Uninsured or periods without coverage")

uninsured %>% 
  group_by(ChildHealthStatus) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

ggplot(childhealthdata) +
  geom_bar(aes(x = ChildHealthStatus, fill = InsGap_1920))

uninsuredgrouped <- uninsured %>% 
  group_by(RaceCat) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

databyrace <- childhealthdata %>% 
  group_by(RaceCat) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)

```

```{r esquisse graphs}

library(ggplot2)

#Flourishing by ACE 
ggplot(childhealthdata) +
 aes(x = FlourishStatus6to17, fill = ACECount) +
 geom_bar() +
 scale_fill_manual(values = c(`0` = "#F8766D", 
`1` = "#DD8A1D", `2` = "#78AC0A", `3` = "#0DB832", `4` = "#00BE79", `5` = "#00BEB7", 
`6` = "#08B6E5", `7` = "#4FA1F9", `8` = "#A385FC", `9` = "#E46DEB", `10` = "#B59C00", Missing = "#FF61C3")) +
 labs(x = "Flourishing Items Met", 
 y = "Children", title = "\"Flourishing\" Status by ACE Count", subtitle = "Count of Children Meeting Flourishing Criteria by Number of Adverse Childhood Experiences", 
 caption = "Based on National Survey of Children's Health, 2019-2020") +
 theme_minimal()

#second flourishing by ace - "Stacked"

dataforACEplot <- childhealthdata      

dataforACEplot$ACECount <- factor(dataforACEplot$ACECount,  
levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Missing"))

dataforACEplot %>% 
  filter(!(FlourishStatus6to17 %in% "Unknown")) %>%
  filter(!(FlourishStatus6to17 %in% "NA, Under 5")) %>%
  filter(!(ACECount %in% "Missing")) %>%
ggplot() +
 aes(x = FlourishStatus6to17, fill = ACECount) +
 geom_bar(position = "fill") +
 scale_fill_hue(direction = 1) +
 labs(x = "Flourishing Items Met", y = "Children", title = "Flourishing Status & Adverse Childhood Experiences (ACE)",
 subtitle = "Count of Children in the US Meeting Flourishing Criteria by Number of Adverse Childhood Experiences", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()


#Health by Ace stacked

childhealthdata$ACECount <- factor(childhealthdata$ACECount,
  levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Missing"))

childhealthdata %>%
  filter(!(ChildHealthStatus %in% "Unknown")) %>%
  filter(!(ACECount %in% "Missing")) %>%
ggplot() +
 aes(x = ChildHealthStatus, fill = ACECount) +
 geom_bar(position = "fill") +
 scale_fill_hue(direction = 1) +
 labs(x = "Health Status", y = "Number of Children", title = "Overall Health Status & Adverse Childhood Experiences (ACE) in the US", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()

#inNJ
NewJersey$ACECount <- factor(NewJersey$ACECount,
  levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Missing"))

NewJersey %>%
  filter(!(ChildHealthStatus %in% "Unknown")) %>%
  filter(!(ACECount %in% "Missing")) %>%
ggplot() +
 aes(x = ChildHealthStatus, fill = ACECount) +
 geom_bar(position = "fill") +
 scale_fill_hue(direction = 1) +
 labs(x = "Health Status", y = "Number of Children", title = "Overall Health Status & Adverse Childhood Experiences (ACE)", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()

#ACE by Race

ggplot(Black) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experiences: Black Children", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: Black Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(White) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: White Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(Asian) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: Asian Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(Hispanic) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience",
 y = "Number of Children", title = "Adverse Childhood Experiences by Race: Hispanic Children", caption = "Based on National Survey of Children's Health, 2019-2020")

ggplot(OtherRace) +
 aes(x = ACECount) +
 geom_bar(fill = "#B22222") +
 labs(x = "Number of Adverse Childhood Experience: Other Race", 
 y = "Number of Children", title = "Adverse Childhood Experiences by Race", caption = "Based on National Survey of Children's Health, 2019-2020")

#ACEbyRACE one plot 

dataforACEplot$RaceCat <- factor(dataforACEplot$RaceCat,  
levels = c("Asian", "Hispanic", "Other", "White", "Black", "Unknown"))

dataforACEplot %>%
 filter(!(RaceCat %in% "Unknown")) %>%
 filter(!(ACECount %in% "Missing")) %>%
 ggplot() +
 aes(x = RaceCat, fill = ACECount) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", 
 direction = 1) +
 labs(x = "Race", y = "Proportion of Children", title = "Adverse Childhood Experiences (ACE) by Race in the US", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()



#Insurance and needed care 
childhealthdata$WentWithoutCare <- factor(childhealthdata$WentWithoutCare,
  levels = c("No", "Yes", "Unknown"))

#needed care by insurance status
childhealthdata %>%
 filter(!(InsGap_1920 %in% "Unknown")) %>%
 filter(!(WentWithoutCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = WentWithoutCare, fill = InsGap_1920) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", direction = 1) +
 labs(x = "Whether Child Missed out on Needed Care", 
 y = "Proportion of Children", title = "Children Receiving Necessary Care by Insurance Status", caption = "Based on National Survey of Children's Health, 2019-2020", 
 fill = "Insured Status") +
 theme_minimal()

#inNJ
NewJersey %>%
 filter(!(InsGap_1920 %in% "Unknown")) %>%
 filter(!(WentWithoutCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = WentWithoutCare, fill = InsGap_1920) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", direction = 1) +
 labs(x = "Whether Child Missed out on Needed Care", 
 y = "Proportion of Children", title = "Children in New Jersey Receiving Care by Insurance Status", caption = "Based on National Survey of Children's Health, 2019-2020",
 fill = "Insured Status") +
 theme_minimal()


```

```{r waffles}
# VectorWhite %>% count(ChildHealthStatus)
WentWithoutWaffle <- c(Yes = 1, No = 44)

# Waffle chart
waffle(WentWithoutWaffle, rows = 5,
       legend_pos = "bottom")

#waffles for Race and Health Status

#WHITE
FlrishWhiteWaffle <- c("0-1 Items" = 19.1, "2 Items" = 19.4, "All 3 Items" = 61.5)

waffle(FlrishWhiteWaffle, rows = 10,
       legend_pos = "bottom")
#BLACK
FlrishBlackWaffle <- c("0-1 Items" = 20, "2 Items" = 18.8, "All 3 Items" = 61.2)

waffle(FlrishBlackWaffle, rows = 10,
       legend_pos = "bottom")

#HISPANIC
FlrishHispanicWaffle <- c("0-1 Items" = 16.8, "2 Items" = 19.6, "All 3 Items" = 63.6)

waffle(FlrishHispanicWaffle, rows = 10,
       legend_pos = "bottom")

#ASIAN
FlrishAsianWaffle <- c("0-1 Items" = 11.8, "2 Items" = 14.8, "All 3 Items" = 73.4)

waffle(FlrishAsianWaffle, rows = 10,
       legend_pos = "bottom")

#Poverty Waffle
NJPovWaffle <- c("Less than 200% FPL" = 24.4, "200% FPL or Greater" = 75.6)

waffle(NJPovWaffle, rows = 10,
       legend_pos = "bottom")

#neededcare 

NJCareWaffle <- c("Missed Out on Needed Care" = 2.2, "Received or Did Not Need Care" = 97.8)

waffle(NJCareWaffle, rows = 10,
       legend_pos = "bottom")

#uninsuredpoverty
#proportion of poor uninsured

NJpoor <- NewJersey %>%
  filter(povlevel == "Less than 200% FPL")

NJInsPovWaffle <- c("Insured" = 87, "Not Consistently Insured" = 13)

waffle(NJInsPovWaffle, rows = 10,
       legend_pos = "bottom")

#plot showing over 50% of poor are uninsured 

NewJersey %>%
 filter(!(InsGap_1920 %in% "Unknown")) %>%
 ggplot() +
 aes(x = InsGap_1920, fill = povlevel) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", 
 direction = 1) +
 labs(x = "Insurance Status", y = "Percentage", title = "Insurance Status and Poverty Level in New Jersey", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Poverty Level") +
 coord_flip() +
 theme_minimal()


```

