---
title: 'Final Project: Child Welfare in the US'
output:
  flexdashboard::flex_dashboard:
    theme: lumen
    vertical_layout: fill
runtime: shiny
resource_files:
- FinalDataforSubmission.csv

---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(DataExplorer)
library(ggplot2)
library(plotly)
library(shiny)
library(devtools)
library(waffle)
library(rsconnect)

# read in data 
childhealthdata <- read_csv("FinalDataforSubmission.csv")

#("C:/Users/rebec/Documents/GitHub/FinalProject_A/2019-2020 National Survey of Children's Health (NSCH)/FinalDataforSubmission.csv")

#adding filtered variables 
NewJersey <- childhealthdata %>%
  filter(State.FIPS.Code == "34")

Poor <- childhealthdata %>%
  filter(povlevel == "Less than 200% FPL")

MissedNeededCare <- childhealthdata %>%
  filter(ForegoneCare == "Yes")

parentEmoSup <- childhealthdata %>%
  filter(SomeoneEmoSup == 1)

yesbehaviorprobsALL <- childhealthdata %>%
  filter(behavior_1920 == "Yes")

White <- childhealthdata %>%
  filter(RaceCat == "White")

Black <- childhealthdata %>%
  filter(RaceCat == "Black")

Asian <- childhealthdata %>%
  filter(RaceCat == "Asian")

Hispanic <- childhealthdata %>%
  filter(RaceCat == "Hispanic")

OtherRace <- childhealthdata %>%
  filter(RaceCat == "Other")

uninsured <- childhealthdata %>%
  filter(InsGap_1920 == "Periods Uninsured")

childhealthdata <- childhealthdata %>% mutate(AceCount = recode_factor(ACEct_1920,
  "0" = "0",
  "1" = "1",
  "2" = "2",
  "3" = "3",
  "4" = "4",
  "5" = "5",
  "6" = "6", 
  "7" = "7",
  "8" = "8",
  "9" = "9",
  "10" = "10",
  "99" = "Missing",
  .ordered = TRUE,
  .default = "Unknown"))

childhealthdata <- childhealthdata %>% mutate(povlevel = recode_factor(povlev4_1920, 
  "1" = "Below 100% FPL",
  "2" = "100-199% FPL",
  "3" = "200-399% FPL",
  "4" = "Greater than 400% FPL",
  .ordered = TRUE,
  .default = "Unknown"))

```

Demographics 
===================================== 
About this Project {.sidebar}
--------------------------------------------------------------
This project was created for submission as a part of Rutgers Data Visualization course. It focuses on child wellbeing in the United States, as evidenced by the National Survey of Children's Health, 2019-2020. 

This dashboard displays demographics of children surveyed, as trends related to insurance status, receiving care, poverty, and Adverse Childhood Experiences (ACE).  

Created by [Rebecca Connelly]

Column {data-height=450} 
-------------------------------------------------------------

### Race of Child

```{r race}
#race 

RaceCount <- childhealthdata %>% 
  group_by(RaceCat) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)


RaceWaffle2 <- c("Black: 686" = 1.37, "Asian: 3,920" = 7.84, "White: 5,268" = 11, "Hispanic: 55,895" = 112, "Other 504" = 1)


RaceWafflePlot2 <- waffle(RaceWaffle2, rows = 11,)

RaceWafflePlot2

```


### Insurance Coverage
```{r insurance pie chart}

InsStatus <- childhealthdata %>% 
  group_by(InsGap_1920) %>% 
  count() %>% arrange(desc(n)) %>%
  rename("children" = n)
InsStatus <- InsStatus %>% filter(InsGap_1920 != "Unknown")

InsStatus$percentage <- InsStatus$children/sum(InsStatus$children)*100
InsStatus$Round_off <- round(InsStatus$percentage) 

#in plotly

piecolors <- c('rgb(144,103,167)', 'rgb(211,94,96)')

InsurancePieChart <- plot_ly(InsStatus, labels = ~InsGap_1920, values = ~children, type = 'pie', 
        textposition = 'outside',
        textinfo = 'percent',
        insidetextfont = list(color = '#FFFFFF'),
        hoverinfo = 'text',
        text = ~paste(children),
        marker = list(colors = piecolors),
                      line = list(color = '#FFFFFF', width = 1),
        showlegend = TRUE)

InsurancePieChart <- InsurancePieChart %>% layout(title = 'Insurance Coverage',
      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

InsurancePieChart

#pie chart source: https://plotly.com/r/pie-charts/
```

Column
-------------------------------------------------------------

### Age of Child 

```{r child age}

childhealthdata <- childhealthdata %>% rename(Age = Child.Age)

ageplot <- ggplot(childhealthdata) +
  aes(x = Age) +
  geom_histogram(bins = 35L, fill = "#1C7D1C") +
  labs(
    x = "Age of Child",
    y = "Number of Children",
    title = "Ages of Children",
    subtitle = "Age Distribution of Child of Interest, with an over sampling of 

    children with disabilities and children ages 0-5",
    caption = "Data Source: National Survey of Children's Health, 2019-2020"
  ) +
  coord_flip() +
    theme_minimal()

ggplotly(ageplot) %>%
layout(title = list(text = paste0('Ages of Children',
                                    '<br>',
                                    '<sup>',
                                    'Age distribution of children sampled, with an over sampling of children with disabilities and children ages 0-5',
                                    '</sup>')),
  annotations = 
 list(x = 1, y = -0.1, text = "Data Source: National Survey of Children's Health, 2019-2020", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=0, yshift=0,
      font=list(size=10, color="black")))

#^source for caption in plotly code = https://stackoverflow.com/questions/45103559/plotly-adding-a-source-or-caption-to-a-chart
#soure code for title in plotly - https://datascott.com/blog/subtitles-with-ggplotly/

```

### Poverty 

```{r poverty level chart}
povplot <- ggplot(childhealthdata) +
  aes(x = povlevel) +
  geom_bar(fill = "#1C7D1C") +
  labs(
    x = "Relation to Federal Poverty Level",
    y = "Number of Children",
  title = "Poverty Level") +
    theme_minimal()


#making it in plotly
ggplotly(povplot) %>%
layout(title = list(text = paste0('Poverty Levels',
                                    '<br>',
                                    '<sup>',
                                    'Povery of children sampled',
                                    '</sup>')))
```


Access {orientation=rows}
=====================================

Column
-----------------------------------------------------------------------

### Uninsured Stats

```{r value box uninsured}

valueBox("6.15%", caption = "Percent Uninsured", icon = NULL, color = NULL, href = NULL)

```

### Poverty Stats

```{r value box poverty}
valueBox("28.71%", caption = "Percent in Poverty", icon = NULL, color = NULL, href = NULL)
```

### Needed Treatment Stats

```{r value box treatment }
valueBox("3.1%", caption = "Percent Who Need Treatment & Did not Receive It", icon = NULL, color = NULL, href = NULL)
```


Column
-------------------------------------------------------------

### Care Not Received

```{r reasons care not received }
numineligible <- childhealthdata %>% filter(ineligible_1920 == 1) %>% count()

numunavailable <- childhealthdata %>% filter(unavailable_1920 == 1) %>% count()

numnoappt <- childhealthdata %>% filter(appointment_1920 == 1) %>% count()

numntransport <- childhealthdata %>% filter(transport_1920 == 1) %>% count()

numNotOpen <- childhealthdata %>% filter(NotOpen_1920 == 1) %>% count()

numCostIssue <- childhealthdata %>% filter(CostIssue_1920 == 1) %>% count()

reasons <- c("Not Eligible", "Unavailable in Area", "Couldn't Get Appointment", "Transportation or Childcare Issues", "Office Wasn't Open", "Cost")
reasonscount <- c(518, 602, 1129, 230, 596, 1118)

reasonsnocaredata <- data.frame(reasons, reasonscount)

reasonsnocareplot <- ggplot(reasonsnocaredata) +
  aes(x = reasons, y = reasonscount) +
  geom_bar(stat = "identity", fill = "#1C7D1C") +
  labs(
    x = "Reason Healthcare Not Received",
    y = "Number of Children",
    title = "Reasons for Missing Needed Care") +
  coord_flip() +
    theme_minimal()

reasonsnocareplot
```

Column {.tabset}
-------------------------------------------------------------

### Needed Care by Insurance 

```{r care insurance}
#insured status by received care
CareInsChart <- childhealthdata %>%
 filter(!(InsGap_1920 %in% "Unknown")) %>%
 filter(!(ForegoneCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = ForegoneCare, fill = InsGap_1920) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "viridis", direction = 1) +
 labs(x = "Whether Child Missed out on Needed Care", 
 y = "Proportion of Children", title = "Children Receiving Necessary Care by Insurance Status", caption = "Based on National Survey of Children's Health, 2019-2020", 
 fill = "Insured Status") +
 theme_minimal()

ggplotly(CareInsChart)
```

### Needed Care By Poverty Level 

```{r care by poverty}
CarePovChart <- childhealthdata %>%
 filter(!(ForegoneCare %in% "Unknown")) %>%
 ggplot() +
 aes(x = ForegoneCare, fill = povlevel) +
 geom_bar(position = "fill") +
 scale_fill_viridis_d(option = "cividis", 
 direction = 1) +
 labs(x = "Missed Out on Needed Care", y = "Proportion of Children", title = "Children Who Did Not Receive Needed Care by Poverty Level", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Poverty Level") +
 theme_minimal()

ggplotly(CarePovChart)
```


### Needed Care by Race 

```{r}
#TBD
```

Column {.tabset}
-------------------------------------------------------------
### Insurance Coverage by Race

```{r}
#TBD
```


### Insurance Coverage by Poverty Level 

```{r}
#TBD
```


Outcomes and Wellbeing {orientation=rows}
=====================================

Column
-------------------------------------------------------------

### ACEs by Racial Category
```{r ACEs and Race}
ACEandRACE <- childhealthdata %>%
  filter(!(RaceCat %in% "Unknown")) %>%
  filter(!(AceCount %in% "Missing")) %>%
 ggplot() +
 aes(x = RaceCat, fill = AceCount) +
 geom_bar(position = "fill") +
  coord_flip() +
 scale_fill_viridis_d(option = "viridis", 
 direction = 1) +
 labs(x = "Race", y = "Proportion of Children", title = "Adverse Childhood Experiences (ACE) by Race in the US", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()

ggplotly(ACEandRACE)
```

Column
-------------------------------------------------------------
### ACEs and Flourishing Status
```{r ACE and Flourish}


FlrshAcePlot <- childhealthdata %>% 
  filter(!(FlourishStatus6to17 %in% "Unknown")) %>%
  filter(!(FlourishStatus6to17 %in% "NA, Under 5")) %>%
  filter(!(AceCount %in% "Missing")) %>%
  filter(!(AceCount %in% "Unknown")) %>%
ggplot() +
 aes(x = FlourishStatus6to17, fill = AceCount) +
 geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_viridis_d(option = "viridis", 
 direction = 1) +
 labs(x = "Flourishing Items Met", y = "Proportion of Children", title = "Flourishing Status & Adverse Childhood Experiences (ACE)",
 subtitle = "Count of Children in the US Meeting Flourishing Criteria by Number of Adverse Childhood Experiences", 
 caption = "Based on National Survey of Children's Health, 2019-2020", fill = "Number of ACEs") +
 theme_minimal()

ggplotly(FlrshAcePlot)
```

